### ISSUE TITLE
Transfer ownership of `registry` on npm?

### ISSUE THREAD

**Issue by billiegoose** [DamonOehlman/registry#4]
Hi! Are you the owner of https://npmjs.com/package/registry? I noticed that `registry` hadn't been updated in 4 years and was marked as deprecated, so I was wondering if you would be interested in [transferring](https://docs.npmjs.com/cli/owner) ownership of the package name? I'm writing a [new registry](https://github.com/wmhilton/registry-alpha) based on `local-npm` and thought before I named it `registry-alpha` or `yet-another-registry`, I'd at least ask if I could get the ultimate ideal registry name: `registry`. 😸

**Comment by DamonOehlman** [comment]
@wmhilton I would definitely consider it. but I think I'd like to see more progress on your `registry-alpha` project before doing that.  I've had a quick look at the differences between it an `local-npm` at the moment, and there does seem to be some useful stuff, but it's mainly in upstart configuration and the like.

In the meantime, I'll check for any projects that might have a dependency on the published version of registry and see what would be impacted by passing it over.

**Comment by DamonOehlman** [comment]
OK, it looks like there are no packages depending on it which is good, but these download stats concern me a little:

```
Stats
5 downloads in the last day
42 downloads in the last week
246 downloads in the last month
```

While it's not a lot, it does seem to suggest that it's used in a private project (or projects) somewhere so that might impact them.  I do recall using it in a project for a client back when I was running my own development shop so they could be one of them...

Unfortunately this is the nature of npm.  You can very easily deal with passing across package names for those that have never been used, but even if there has been some activity (I had this happen on another project) then it have a pretty big impact on folks.

**Comment by billiegoose** [comment]
Ah, I was hoping the 5 download a day might just be from npm mirrors, but you may be right. In _theory_ I could just release the new package as major version bump (breaking changes) and if downstream is using semantic versioning they wouldn't experience any problems... But who are we kidding? If you've got clients who might still be using it, then don't touch it. The whole reason I'm working in the registry problem space is because npm kept breaking on me. I'll come up with an original name! I am feeling more creative now than when I chose "registry-alpha".

**Comment by billiegoose** [comment]
> but I think I'd like to see more progress on your registry-alpha project before doing that.

The point's moot because I don't want to rock the client-who-might-be-using-it boat, but if you're still curious, the longest coherent discussion that might be interpreted as a "roadmap" can be found here:
https://github.com/wmhilton/registry-alpha/issues/2
